{"name": "Логин несуществующего пользователя", "status": "passed", "description": "Проверяем, что если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "start": 1721556142986, "stop": 1721556143462, "uuid": "95fb0210-5d72-49d0-baa5-b4f11b2aa7d2", "historyId": "1d065f57ee5a26169cfb491c99795c84", "testCaseId": "1d065f57ee5a26169cfb491c99795c84", "fullName": "tests.test_login_courier.TestLoginCourier#test_non_existent_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "MacBook-Pro-4.local"}, {"name": "thread", "value": "64175-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}